global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "caddy"
    static_configs:
      - targets: ["caddy:2019"]
  
  - job_name: “node-exporter”
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
