{
 "title": "caddy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!=\"tmpfs\"} - node_filesystem_free_bytes{fstype!=\"tmpfs\"}) / node_filesystem_size_bytes{fstype!=\"tmpfs\"} * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - ((node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}) / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic Dashboard (bytes)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!=\"lo\"}[5m]) + irate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])) by (device)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Caddy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Caddy service health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dummy http service health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(promhttp_metric_handler_requests_total{code!=\"200\",instance=\"caddy:2019\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server errors (5xx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_request_duration_seconds_count{code=~\"5.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client errors (4xx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_request_duration_seconds_count{code=~\"4.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Request Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caddy_http_response_duration_seconds_sum{code=\"200\",instance=\"caddy:2019\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}